/*
 * Auto-generated from enterprises/enterprise_calix_ipfix.csv
 * Do not edit by hand — re-run: python3 enterprises/gen_calix_ies.py
 */

#ifndef IPFIX_ENTERPRISE_CALIX_H
#define IPFIX_ENTERPRISE_CALIX_H

/** Calix Private Enterprise Number (IANA PEN). */
#define IPFIX_PEN_CALIX 6321u

/* Calix E7 / AXOS Information Element IDs (enterprise IPFIX_PEN_CALIX). */
#define IPFIX_CALIX_IE_hostname                                 1u  /* hostname */
#define IPFIX_CALIX_IE_shelf                                    2u  /* shelf */
#define IPFIX_CALIX_IE_slot                                     3u  /* slot */
#define IPFIX_CALIX_IE_port                                     4u  /* port */
#define IPFIX_CALIX_IE_ont_id                                   7u  /* ont-id */
#define IPFIX_CALIX_IE_svlan                                    8u  /* svlan */
#define IPFIX_CALIX_IE_cvlan                                    9u  /* cvlan */
#define IPFIX_CALIX_IE_sample_time                              10u  /* sample-time */
#define IPFIX_CALIX_IE_group                                    12u  /* group */
#define IPFIX_CALIX_IE_bin_duration                             20u  /* bin-duration */
#define IPFIX_CALIX_IE_bin_number                               21u  /* bin-number */
#define IPFIX_CALIX_IE_start_time                               22u  /* start-time */
#define IPFIX_CALIX_IE_end_time                                 23u  /* end-time */
#define IPFIX_CALIX_IE_time_elapsed                             24u  /* time-elapsed */
#define IPFIX_CALIX_IE_suspect                                  25u  /* suspect */
#define IPFIX_CALIX_IE_cause                                    26u  /* cause */
#define IPFIX_CALIX_IE_mac                                      56u  /* mac */
#define IPFIX_CALIX_IE_OLT_pon_util_aid                         103u  /* OLT-pon-util-aid */
#define IPFIX_CALIX_IE_OLT_ponoptical_aid                       105u  /* OLT-ponoptical-aid */
#define IPFIX_CALIX_IE_OLT_ont_bin_aid                          106u  /* OLT-ont-bin-aid */
#define IPFIX_CALIX_IE_ONT_eth_util_aid                         107u  /* ONT-eth-util-aid */
#define IPFIX_CALIX_IE_ONT_eth_total_aid                        114u  /* ONT-eth-total-aid */
#define IPFIX_CALIX_IE_dhcp_poolaid                             115u  /* dhcp-poolaid */
#define IPFIX_CALIX_IE_bng_gx_counter_aid                       118u  /* bng-gx-counter-aid */
#define IPFIX_CALIX_IE_bng_urlredirectaid                       119u  /* bng-urlredirectaid */
#define IPFIX_CALIX_IE_bng_policymgmt_aid                       120u  /* bng-policymgmt-aid */
#define IPFIX_CALIX_IE_bng_arp_countersaid                      121u  /* bng-arp-countersaid */
#define IPFIX_CALIX_IE_bng_diameterclient_aid                   122u  /* bng-diameterclient-aid */
#define IPFIX_CALIX_IE_bng_radiusclientaid                      123u  /* bng-radiusclientaid */
#define IPFIX_CALIX_IE_interfaceethernet_aid                    130u  /* interfaceethernet-aid */
#define IPFIX_CALIX_IE_interface_lag_aid                        131u  /* interface-lag-aid */
#define IPFIX_CALIX_IE_eth_vlan_monitor_aid                     132u  /* eth-vlan-monitor-aid */
#define IPFIX_CALIX_IE_lag_vlan_monitor_aid                     133u  /* lag-vlan-monitor-aid */
#define IPFIX_CALIX_IE_pon_ont_type_utilaid                     134u  /* pon-ont-type-utilaid */
#define IPFIX_CALIX_IE_sys_info_aid                             148u  /* sys-info-aid */
#define IPFIX_CALIX_IE_tx_octets                                200u  /* tx-octets */
#define IPFIX_CALIX_IE_tx_pkts                                  201u  /* tx-pkts */
#define IPFIX_CALIX_IE_tx_discards                              202u  /* tx-discards */
#define IPFIX_CALIX_IE_tx_errors                                203u  /* tx-errors */
#define IPFIX_CALIX_IE_rx_octets                                204u  /* rx-octets */
#define IPFIX_CALIX_IE_rx_pkts                                  205u  /* rx-pkts */
#define IPFIX_CALIX_IE_rx_discards                              206u  /* rx-discards */
#define IPFIX_CALIX_IE_rx_errors                                207u  /* rx-errors */
#define IPFIX_CALIX_IE_upstream_octets                          208u  /* upstream-octets */
#define IPFIX_CALIX_IE_downstream_octets                        209u  /* downstream-octets */
#define IPFIX_CALIX_IE_admitted_fixed_upstreambw                210u  /* admitted-fixed-upstreambw */
#define IPFIX_CALIX_IE_available_fixed_upstreambw               211u  /* available-fixed-upstreambw */
#define IPFIX_CALIX_IE_admitted_excessupstream_bw               212u  /* admitted-excessupstream-bw */
#define IPFIX_CALIX_IE_available_excessupstream_bw              213u  /* available-excessupstream-bw */
#define IPFIX_CALIX_IE_power_feedvoltage1                       230u  /* power-feedvoltage1 */
#define IPFIX_CALIX_IE_rx_opticalpower2                         231u  /* rx-opticalpower2 */
#define IPFIX_CALIX_IE_mean_opticallaunch_power2                232u  /* mean-opticallaunch-power2 */
#define IPFIX_CALIX_IE_laser_biascurrent2                       233u  /* laser-biascurrent2 */
#define IPFIX_CALIX_IE_temperature                              234u  /* temperature */
#define IPFIX_CALIX_IE_optical_channel                          235u  /* optical-channel */
#define IPFIX_CALIX_IE_upstream_biperrors                       240u  /* upstream-biperrors */
#define IPFIX_CALIX_IE_upstream_missedbursts                    241u  /* upstream-missedbursts */
#define IPFIX_CALIX_IE_upstream_gemhec_errors                   242u  /* upstream-gemhec-errors */
#define IPFIX_CALIX_IE_upstream_bip8_err_sec                    243u  /* upstream-bip8-err-sec */
#define IPFIX_CALIX_IE_upstream_bip8_severelyerr_sec            244u  /* upstream-bip8-severelyerr-sec */
#define IPFIX_CALIX_IE_upstream_bip8_unavail_sec                245u  /* upstream-bip8-unavail-sec */
#define IPFIX_CALIX_IE_upstream_missedbursts_err_sec            246u  /* upstream-missedbursts-err-sec */
#define IPFIX_CALIX_IE_upstream_feccorrectedbytes               247u  /* upstream-feccorrectedbytes */
#define IPFIX_CALIX_IE_upstream_feccorrectedcode_words          248u  /* upstream-feccorrectedcode-words */
#define IPFIX_CALIX_IE_upstream_fecuncorrectedcode_words        249u  /* upstream-fecuncorrectedcode-words */
#define IPFIX_CALIX_IE_upstream_fectotal_codewords              250u  /* upstream-fectotal-codewords */
#define IPFIX_CALIX_IE_upstream_fecsec                          251u  /* upstream-fecsec */
#define IPFIX_CALIX_IE_downstream_bip_errors                    252u  /* downstream-bip-errors */
#define IPFIX_CALIX_IE_downstream_bip8_err_sec                  253u  /* downstream-bip8-err-sec */
#define IPFIX_CALIX_IE_downstream_bip8_severely_err_sec         254u  /* downstream-bip8-severely-err-sec */
#define IPFIX_CALIX_IE_unavail_sec                              255u  /* unavail-sec */
#define IPFIX_CALIX_IE_downstream_feccorrected_bytes3           256u  /* downstream-feccorrected-bytes3 */
#define IPFIX_CALIX_IE_downstream_feccorrectedcode_words3       257u  /* downstream-feccorrectedcode-words3 */
#define IPFIX_CALIX_IE_downstream_fecuncorrectedcode_words3     258u  /* downstream-fecuncorrectedcode-words3 */
#define IPFIX_CALIX_IE_downstream_fectotal_codewords3           259u  /* downstream-fectotal-codewords3 */
#define IPFIX_CALIX_IE_downstream_fecsec3                       260u  /* downstream-fecsec3 */
#define IPFIX_CALIX_IE_fcs_errors                               270u  /* fcs-errors */
#define IPFIX_CALIX_IE_excessivecollision                       271u  /* excessivecollision */
#define IPFIX_CALIX_IE_late_collision                           272u  /* late-collision */
#define IPFIX_CALIX_IE_frame_too_long                           273u  /* frame-too-long */
#define IPFIX_CALIX_IE_buffer_overflowxmit                      274u  /* buffer-overflowxmit */
#define IPFIX_CALIX_IE_buffer_overflowrecv                      275u  /* buffer-overflowrecv */
#define IPFIX_CALIX_IE_single_collision                         276u  /* single-collision */
#define IPFIX_CALIX_IE_multiple_collision                       277u  /* multiple-collision */
#define IPFIX_CALIX_IE_sqe_counter                              278u  /* sqe-counter */
#define IPFIX_CALIX_IE_deferred_xmitcount                       279u  /* deferred-xmitcount */
#define IPFIX_CALIX_IE_internal_macxmit_error                   280u  /* internal-macxmit-error */
#define IPFIX_CALIX_IE_internal_macrecv_error                   281u  /* internal-macrecv-error */
#define IPFIX_CALIX_IE_carrier_senseerror                       282u  /* carrier-senseerror */
#define IPFIX_CALIX_IE_alignment_error                          283u  /* alignment-error */
#define IPFIX_CALIX_IE_upstream_drop_events                     284u  /* upstream-drop-events */
#define IPFIX_CALIX_IE_upstream_packets                         285u  /* upstream-packets */
#define IPFIX_CALIX_IE_upstream_broadcastpackets                286u  /* upstream-broadcastpackets */
#define IPFIX_CALIX_IE_upstream_multicastpackets                287u  /* upstream-multicastpackets */
#define IPFIX_CALIX_IE_upstream_unicastpackets                  288u  /* upstream-unicastpackets */
#define IPFIX_CALIX_IE_upstream_crc_erroredpackets              289u  /* upstream-crc-erroredpackets */
#define IPFIX_CALIX_IE_upstream_oversizepackets                 290u  /* upstream-oversizepackets */
#define IPFIX_CALIX_IE_upstream_undersizepackets                291u  /* upstream-undersizepackets */
#define IPFIX_CALIX_IE_upstream_packets_64_octets               292u  /* upstream-packets-64-octets */
#define IPFIX_CALIX_IE_upstream_packets_65_to_127_octets        293u  /* upstream-packets-65-to-127-octets */
#define IPFIX_CALIX_IE_upstream_packets_128_to_255_octets       294u  /* upstream-packets-128-to-255-octets */
#define IPFIX_CALIX_IE_upstream_packets_256_to_511_octets       295u  /* upstream-packets-256-to-511-octets */
#define IPFIX_CALIX_IE_upstream_packets_512_to_1023_octets      296u  /* upstream-packets-512-to-1023-octets */
#define IPFIX_CALIX_IE_upstream_packets_1024_to_1518_octets     297u  /* upstream-packets-1024-to-1518-octets */
#define IPFIX_CALIX_IE_downstream_drop_events                   298u  /* downstream-drop-events */
#define IPFIX_CALIX_IE_downstream_packets                       299u  /* downstream-packets */
#define IPFIX_CALIX_IE_downstream_broadcastpackets              300u  /* downstream-broadcastpackets */
#define IPFIX_CALIX_IE_downstream_multicastpackets              301u  /* downstream-multicastpackets */
#define IPFIX_CALIX_IE_downstream_unicastpackets                302u  /* downstream-unicastpackets */
#define IPFIX_CALIX_IE_downstream_crc_erroredpackets            303u  /* downstream-crc-erroredpackets */
#define IPFIX_CALIX_IE_downstream_oversizepackets               304u  /* downstream-oversizepackets */
#define IPFIX_CALIX_IE_downstream_undersizepackets              305u  /* downstream-undersizepackets */
#define IPFIX_CALIX_IE_downstream_galdiscarded_frames           306u  /* downstream-galdiscarded-frames */
#define IPFIX_CALIX_IE_upstream_gem_frames                      307u  /* upstream-gem-frames */
#define IPFIX_CALIX_IE_upstream_gem_payloadbytes                308u  /* upstream-gem-payloadbytes */
#define IPFIX_CALIX_IE_downstream_gem_frames                    309u  /* downstream-gem-frames */
#define IPFIX_CALIX_IE_downstream_gempayload_bytes              310u  /* downstream-gempayload-bytes */
#define IPFIX_CALIX_IE_gem_encryption_keyerrors                 311u  /* gem-encryption-keyerrors */
#define IPFIX_CALIX_IE_upstream_gal_discardedframes             312u  /* upstream-gal-discardedframes */
#define IPFIX_CALIX_IE_admitted_assuredupstream_bw              320u  /* admitted-assuredupstream-bw */
#define IPFIX_CALIX_IE_available_assuredupstream_bw             321u  /* available-assuredupstream-bw */
#define IPFIX_CALIX_IE_fixed_upstreambytes                      322u  /* fixed-upstreambytes */
#define IPFIX_CALIX_IE_assured_upstream_bytes                   323u  /* assured-upstream-bytes */
#define IPFIX_CALIX_IE_flow_number                              331u  /* flow-number */
#define IPFIX_CALIX_IE_ingress_bucketseconds                    340u  /* ingress-bucketseconds */
#define IPFIX_CALIX_IE_ingress_bucket_bps                       341u  /* ingress-bucket-bps */
#define IPFIX_CALIX_IE_ingress_bucketpercent                    342u  /* ingress-bucketpercent */
#define IPFIX_CALIX_IE_egress_bucketseconds                     343u  /* egress-bucketseconds */
#define IPFIX_CALIX_IE_egress_bucket_bps                        344u  /* egress-bucket-bps */
#define IPFIX_CALIX_IE_egress_bucketpercent                     345u  /* egress-bucketpercent */
#define IPFIX_CALIX_IE_doze_time                                370u  /* doze-time */
#define IPFIX_CALIX_IE_cyclic_sleep_time                        371u  /* cyclic-sleep-time */
#define IPFIX_CALIX_IE_watchful_sleep_time                      372u  /* watchful-sleep-time */
#define IPFIX_CALIX_IE_energy_consumed                          373u  /* energy-consumed */
#define IPFIX_CALIX_IE_cpu_percent_utilization                  374u  /* cpu-percent-utilization */
#define IPFIX_CALIX_IE_ram_available_amount                     375u  /* ram-available-amount */
#define IPFIX_CALIX_IE_ram_utilization                          376u  /* ram-utilization */
#define IPFIX_CALIX_IE_flash_available_amount                   377u  /* flash-available-amount */
#define IPFIX_CALIX_IE_flash_utilization                        378u  /* flash-utilization */
#define IPFIX_CALIX_IE_software_errors                          379u  /* software-errors */
#define IPFIX_CALIX_IE_errors_in_operations                     380u  /* errors-in-operations */
#define IPFIX_CALIX_IE_upstream_tx_timing_drift                 381u  /* upstream-tx-timing-drift */
#define IPFIX_CALIX_IE_upstream_tx_wavelengthdrift              382u  /* upstream-tx-wavelengthdrift */
#define IPFIX_CALIX_IE_mean_in_channel_power                    383u  /* mean-in-channel-power */
#define IPFIX_CALIX_IE_mean_out_of_channel_psd                  384u  /* mean-out-of-channel-psd */
#define IPFIX_CALIX_IE_mean_psd_short_periodwhen_disabled       385u  /* mean-psd-short-periodwhen-disabled */
#define IPFIX_CALIX_IE_mean_psd_long_periodwhen_disabled        386u  /* mean-psd-long-periodwhen-disabled */
#define IPFIX_CALIX_IE_if_index                                 600u  /* if-index */
#define IPFIX_CALIX_IE_drop_events                              601u  /* drop-events */
#define IPFIX_CALIX_IE_octets                                   602u  /* octets */
#define IPFIX_CALIX_IE_pkts                                     603u  /* pkts */
#define IPFIX_CALIX_IE_broadcast_pkts                           604u  /* broadcast-pkts */
#define IPFIX_CALIX_IE_multicast_pkts                           605u  /* multicast-pkts */
#define IPFIX_CALIX_IE_crc_align_errors                         606u  /* crc-align-errors */
#define IPFIX_CALIX_IE_undersize_pkts                           607u  /* undersize-pkts */
#define IPFIX_CALIX_IE_oversize_pkts                            608u  /* oversize-pkts */
#define IPFIX_CALIX_IE_fragments                                609u  /* fragments */
#define IPFIX_CALIX_IE_pkts_64                                  610u  /* pkts-64 */
#define IPFIX_CALIX_IE_pkts_65to127                             611u  /* pkts-65to127 */
#define IPFIX_CALIX_IE_pkts_128to255                            612u  /* pkts-128to255 */
#define IPFIX_CALIX_IE_pkts_256to511                            613u  /* pkts-256to511 */
#define IPFIX_CALIX_IE_pkts_512to1023                           614u  /* pkts-512to1023 */
#define IPFIX_CALIX_IE_pkts_1024to1518                          615u  /* pkts-1024to1518 */
#define IPFIX_CALIX_IE_pkts_1519to2047                          616u  /* pkts-1519to2047 */
#define IPFIX_CALIX_IE_pkts_2048to4095                          617u  /* pkts-2048to4095 */
#define IPFIX_CALIX_IE_pkts_4096to9216                          618u  /* pkts-4096to9216 */
#define IPFIX_CALIX_IE_pkts_9217to16383                         619u  /* pkts-9217to16383 */
#define IPFIX_CALIX_IE_rx_unicast_pkts                          620u  /* rx-unicast-pkts */
#define IPFIX_CALIX_IE_rx_multicast_pkts                        621u  /* rx-multicast-pkts */
#define IPFIX_CALIX_IE_rx_broadcast_pkts                        622u  /* rx-broadcast-pkts */
#define IPFIX_CALIX_IE_rx_pause_frames                          623u  /* rx-pause-frames */
#define IPFIX_CALIX_IE_rx_unknown_protos                        624u  /* rx-unknown-protos */
#define IPFIX_CALIX_IE_tx_unicast_pkts                          625u  /* tx-unicast-pkts */
#define IPFIX_CALIX_IE_tx_multicast_pkts                        626u  /* tx-multicast-pkts */
#define IPFIX_CALIX_IE_tx_broadcast_pkts                        627u  /* tx-broadcast-pkts */
#define IPFIX_CALIX_IE_tx_pause_frames                          628u  /* tx-pause-frames */
#define IPFIX_CALIX_IE_align_errors                             629u  /* align-errors */
#define IPFIX_CALIX_IE_jabbers                                  630u  /* jabbers */
#define IPFIX_CALIX_IE_rx_utilization                           631u  /* rx-utilization */
#define IPFIX_CALIX_IE_tx_utilization                           632u  /* tx-utilization */
#define IPFIX_CALIX_IE_rx_pps                                   633u  /* rx-pps */
#define IPFIX_CALIX_IE_tx_pps                                   634u  /* tx-pps */
#define IPFIX_CALIX_IE_rx_bps                                   635u  /* rx-bps */
#define IPFIX_CALIX_IE_tx_bps                                   636u  /* tx-bps */
#define IPFIX_CALIX_IE_rx_unicast_octets                        637u  /* rx-unicast-octets */
#define IPFIX_CALIX_IE_rx_multicast_octets                      638u  /* rx-multicast-octets */
#define IPFIX_CALIX_IE_rx_broadcast_octets                      639u  /* rx-broadcast-octets */
#define IPFIX_CALIX_IE_tx_unicast_octets                        640u  /* tx-unicast-octets */
#define IPFIX_CALIX_IE_tx_multicast_octets                      641u  /* tx-multicast-octets */
#define IPFIX_CALIX_IE_tx_broadcast_octets                      642u  /* tx-broadcast-octets */
#define IPFIX_CALIX_IE_role                                     643u  /* role */
#define IPFIX_CALIX_IE_moduletemperature                        644u  /* moduletemperature */
#define IPFIX_CALIX_IE_module_tx_power                          645u  /* module-tx-power */
#define IPFIX_CALIX_IE_module_vcc                               646u  /* module-vcc */
#define IPFIX_CALIX_IE_module_rx_power                          647u  /* module-rx-power */
#define IPFIX_CALIX_IE_carrier_transitions                      648u  /* carrier-transitions */
#define IPFIX_CALIX_IE_input_power_instant                      649u  /* input-power-instant */
#define IPFIX_CALIX_IE_output_power_instant                     650u  /* output-power-instant */
#define IPFIX_CALIX_IE_configured_poolsize                      801u  /* configured-poolsize */
#define IPFIX_CALIX_IE_leases_in_grace                          802u  /* leases-in-grace */
#define IPFIX_CALIX_IE_active_leases                            803u  /* active-leases */
#define IPFIX_CALIX_IE_max_leases                               804u  /* max-leases */
#define IPFIX_CALIX_IE_min_leases                               805u  /* min-leases */
#define IPFIX_CALIX_IE_avg_leases                               806u  /* avg-leases */
#define IPFIX_CALIX_IE_offers_sent                              807u  /* offers-sent */
#define IPFIX_CALIX_IE_offers_accepted                          808u  /* offers-accepted */
#define IPFIX_CALIX_IE_requestsgranted                          809u  /* requestsgranted */
#define IPFIX_CALIX_IE_requestsdeclined                         810u  /* requestsdeclined */
#define IPFIX_CALIX_IE_requesttimeouts                          811u  /* requesttimeouts */
#define IPFIX_CALIX_IE_lease_renewals                           812u  /* lease-renewals */
#define IPFIX_CALIX_IE_lease_timerexpiries                      813u  /* lease-timerexpiries */
#define IPFIX_CALIX_IE_grace_timerexpiries                      814u  /* grace-timerexpiries */
#define IPFIX_CALIX_IE_tx_ccr_i                                 840u  /* tx-ccr-i */
#define IPFIX_CALIX_IE_rx_cca_i                                 841u  /* rx-cca-i */
#define IPFIX_CALIX_IE_tx_ccr_u                                 842u  /* tx-ccr-u */
#define IPFIX_CALIX_IE_rx_cca_u                                 843u  /* rx-cca-u */
#define IPFIX_CALIX_IE_rx_rar                                   844u  /* rx-rar */
#define IPFIX_CALIX_IE_tx_raa                                   845u  /* tx-raa */
#define IPFIX_CALIX_IE_raa_session_idmismatch                   846u  /* raa-session-idmismatch */
#define IPFIX_CALIX_IE_pcrf_timerexpiries                       847u  /* pcrf-timerexpiries */
#define IPFIX_CALIX_IE_configuredsubscribers_with_pcrfenabled   848u  /* configuredsubscribers-with-pcrfenabled */
#define IPFIX_CALIX_IE_activesubscriberswith_pcrfenabled        849u  /* activesubscriberswith-pcrfenabled */
#define IPFIX_CALIX_IE_active_defaultsubscriberswith_pcrfenabled 850u  /* active-defaultsubscriberswith-pcrfenabled */
#define IPFIX_CALIX_IE_url_redirectsubscribers                  860u  /* url-redirectsubscribers */
#define IPFIX_CALIX_IE_url_redirectpoliciesapplied              861u  /* url-redirectpoliciesapplied */
#define IPFIX_CALIX_IE_url_updates                              862u  /* url-updates */
#define IPFIX_CALIX_IE_dynamic_policyapplyrequests              870u  /* dynamic-policyapplyrequests */
#define IPFIX_CALIX_IE_dynamic_policyapplysuccesses             871u  /* dynamic-policyapplysuccesses */
#define IPFIX_CALIX_IE_dynamic_policyapplyfailures              872u  /* dynamic-policyapplyfailures */
#define IPFIX_CALIX_IE_rx_arp_req                               873u  /* rx-arp-req */
#define IPFIX_CALIX_IE_tx_arp_resp                              874u  /* tx-arp-resp */
#define IPFIX_CALIX_IE_arp_timer_expiries                       875u  /* arp-timer-expiries */
#define IPFIX_CALIX_IE_diameter_client_name                     876u  /* diameter-client-name */
#define IPFIX_CALIX_IE_tx_cer                                   880u  /* tx-cer */
#define IPFIX_CALIX_IE_rx_cea                                   881u  /* rx-cea */
#define IPFIX_CALIX_IE_rtx_msg                                  882u  /* rtx-msg */
#define IPFIX_CALIX_IE_msg_timeout                              883u  /* msg-timeout */
#define IPFIX_CALIX_IE_peer_up                                  884u  /* peer-up */
#define IPFIX_CALIX_IE_peer_down                                885u  /* peer-down */
#define IPFIX_CALIX_IE_watchdogtimerexpiries                    886u  /* watchdogtimerexpiries */
#define IPFIX_CALIX_IE_peerdisconnect                           887u  /* peerdisconnect */
#define IPFIX_CALIX_IE_radius_clientname                        888u  /* radius-clientname */
#define IPFIX_CALIX_IE_tx_accountingstart                       890u  /* tx-accountingstart */
#define IPFIX_CALIX_IE_tx_accountinginterim                     891u  /* tx-accountinginterim */
#define IPFIX_CALIX_IE_tx_accountingstop                        892u  /* tx-accountingstop */
#define IPFIX_CALIX_IE_rtx_accountingstart                      893u  /* rtx-accountingstart */
#define IPFIX_CALIX_IE_rtx_accountinginterim                    894u  /* rtx-accountinginterim */
#define IPFIX_CALIX_IE_rtx_accountingstop                       895u  /* rtx-accountingstop */
#define IPFIX_CALIX_IE_rx_accountingsuccess_resp                896u  /* rx-accountingsuccess-resp */
#define IPFIX_CALIX_IE_rx_accountingfailure_resp                897u  /* rx-accountingfailure-resp */
#define IPFIX_CALIX_IE_upstream_discard_events                  899u  /* upstream-discard-events */
#define IPFIX_CALIX_IE_upstream_crc_error_frames                900u  /* upstream-crc-error-frames */
#define IPFIX_CALIX_IE_downstream_discardevents                 901u  /* downstream-discardevents */
#define IPFIX_CALIX_IE_downstream_crc_errorframes               902u  /* downstream-crc-errorframes */
#define IPFIX_CALIX_IE_pon_ont_util_aid                         903u  /* pon-ont-util-aid */
#define IPFIX_CALIX_IE_upstream_bytes                           904u  /* upstream-bytes */
#define IPFIX_CALIX_IE_downstream_bytes                         905u  /* downstream-bytes */
#define IPFIX_CALIX_IE_upstreampercentage                       906u  /* upstreampercentage */
#define IPFIX_CALIX_IE_downstreampercentage                     907u  /* downstreampercentage */
#define IPFIX_CALIX_IE_bgp_stat_aid                             943u  /* bgp-stat-aid */
#define IPFIX_CALIX_IE_neighbor                                 944u  /* neighbor */
#define IPFIX_CALIX_IE_in_opens                                 945u  /* in-opens */
#define IPFIX_CALIX_IE_out_opens                                946u  /* out-opens */
#define IPFIX_CALIX_IE_in_notifications                         947u  /* in-notifications */
#define IPFIX_CALIX_IE_out_notifications                        948u  /* out-notifications */
#define IPFIX_CALIX_IE_in_updates                               949u  /* in-updates */
#define IPFIX_CALIX_IE_out_updates                              950u  /* out-updates */
#define IPFIX_CALIX_IE_in_keepalives                            951u  /* in-keepalives */
#define IPFIX_CALIX_IE_out_keepalives                           952u  /* out-keepalives */
#define IPFIX_CALIX_IE_in_totalmessages                         953u  /* in-totalmessages */
#define IPFIX_CALIX_IE_out_totalmessages                        954u  /* out-totalmessages */
#define IPFIX_CALIX_IE_oper_state                               955u  /* oper-state */
#define IPFIX_CALIX_IE_admin_state                              956u  /* admin-state */
#define IPFIX_CALIX_IE_oper_speed                               978u  /* oper-speed */
#define IPFIX_CALIX_IE_tx_power                                 979u  /* tx-power */
#define IPFIX_CALIX_IE_tx_voltage                               980u  /* tx-voltage */
#define IPFIX_CALIX_IE_tx_bias                                  981u  /* tx-bias */
#define IPFIX_CALIX_IE_rx_availablebandwidth                    982u  /* rx-availablebandwidth */
#define IPFIX_CALIX_IE_tx_opt_level                             983u  /* tx-opt-level */
#define IPFIX_CALIX_IE_ne_opt_signallevel                       984u  /* ne-opt-signallevel */
#define IPFIX_CALIX_IE_range_length                             985u  /* range-length */
#define IPFIX_CALIX_IE_curr_version                             986u  /* curr-version */
#define IPFIX_CALIX_IE_up_time                                  987u  /* up-time */
#define IPFIX_CALIX_IE_tx_availablebandwidth                    988u  /* tx-availablebandwidth */
#define IPFIX_CALIX_IE_cpu_usage                                992u  /* cpu-usage */
#define IPFIX_CALIX_IE_uptime                                   993u  /* uptime */
#define IPFIX_CALIX_IE_temp_sensor                              994u  /* temp-sensor */
#define IPFIX_CALIX_IE_vrf_name                                 1083u  /* vrf-name */
#define IPFIX_CALIX_IE_vrf_name_1093                            1093u  /* vrf-name */
#define IPFIX_CALIX_IE_bgpv6_stat_aid                           1134u  /* bgpv6-stat-aid */
#define IPFIX_CALIX_IE_vlan                                     1188u  /* vlan */
#define IPFIX_CALIX_IE_neighbor_v6                              1196u  /* neighbor-v6 */
#define IPFIX_CALIX_IE_rx_fec_total_code_words                  1200u  /* rx-fec-total-code-words */
#define IPFIX_CALIX_IE_rx_fec_corrected_codewords               1201u  /* rx-fec-corrected-codewords */
#define IPFIX_CALIX_IE_rx_fec_uncorrected_codewords             1202u  /* rx-fec-uncorrected-codewords */
#define IPFIX_CALIX_IE_ONT_rg_total_aid                         1203u  /* ONT-rg-total-aid */
#define IPFIX_CALIX_IE_OLT_ontrg_bin_aid                        1204u  /* OLT-ontrg-bin-aid */
#define IPFIX_CALIX_IE_ONT_fb_total_aid                         1205u  /* ONT-fb-total-aid */
#define IPFIX_CALIX_IE_ONT_pots_total_aid                       1206u  /* ONT-pots-total-aid */
#define IPFIX_CALIX_IE_ont_ua                                   1207u  /* ont-ua */
#define IPFIX_CALIX_IE_OLT_ontpots_sip_serviceaid               1208u  /* OLT-ontpots-sip-serviceaid */
#define IPFIX_CALIX_IE_sip_profile                              1209u  /* sip-profile */
#define IPFIX_CALIX_IE_service_status                           1210u  /* service-status */
#define IPFIX_CALIX_IE_hook_status                              1211u  /* hook-status */
#define IPFIX_CALIX_IE_OLT_ontpots_mgcp_serviceaid              1212u  /* OLT-ontpots-mgcp-serviceaid */
#define IPFIX_CALIX_IE_mgcp_profile                             1213u  /* mgcp-profile */
#define IPFIX_CALIX_IE_pon_ont_util_total_aid                   1214u  /* pon-ont-util-total-aid */
#define IPFIX_CALIX_IE_upstreampon_rate                         1215u  /* upstreampon-rate */
#define IPFIX_CALIX_IE_downstreampon_rate                       1216u  /* downstreampon-rate */
#define IPFIX_CALIX_IE_vendor_part_number                       1217u  /* vendor-part-number */
#define IPFIX_CALIX_IE_ram_usage                                1220u  /* ram-usage */
#define IPFIX_CALIX_IE_available_memory                         1221u  /* available-memory */
#define IPFIX_CALIX_IE_linked_pon                               1222u  /* linked-pon */
#define IPFIX_CALIX_IE_OLT_gemflow_bin_aid                      1223u  /* OLT-gemflow-bin-aid */
#define IPFIX_CALIX_IE_receivedoptical_power                    2002u  /* receivedoptical-power */
#define IPFIX_CALIX_IE_mpls_stat_aid                            2018u  /* mpls-stat-aid */
#define IPFIX_CALIX_IE_ldp_peer                                 2019u  /* ldp-peer */
#define IPFIX_CALIX_IE_tx_initialization                        2020u  /* tx-initialization */
#define IPFIX_CALIX_IE_rx_initialization                        2021u  /* rx-initialization */
#define IPFIX_CALIX_IE_tx_address                               2022u  /* tx-address */
#define IPFIX_CALIX_IE_rx_address                               2023u  /* rx-address */
#define IPFIX_CALIX_IE_tx_address_withdraw                      2024u  /* tx-address-withdraw */
#define IPFIX_CALIX_IE_rx_address_withdraw                      2025u  /* rx-address-withdraw */
#define IPFIX_CALIX_IE_tx_label_mapping                         2026u  /* tx-label-mapping */
#define IPFIX_CALIX_IE_rx_label_mapping                         2027u  /* rx-label-mapping */
#define IPFIX_CALIX_IE_tx_label_withdraw                        2028u  /* tx-label-withdraw */
#define IPFIX_CALIX_IE_rx_label_withdraw                        2029u  /* rx-label-withdraw */
#define IPFIX_CALIX_IE_tx_label_release                         2030u  /* tx-label-release */
#define IPFIX_CALIX_IE_rx_label_release                         2031u  /* rx-label-release */
#define IPFIX_CALIX_IE_tx_label_request                         2032u  /* tx-label-request */
#define IPFIX_CALIX_IE_rx_label_request                         2033u  /* rx-label-request */
#define IPFIX_CALIX_IE_tx_label_abort_request                   2034u  /* tx-label-abort-request */
#define IPFIX_CALIX_IE_rx_label_abort_request                   2035u  /* rx-label-abort-request */
#define IPFIX_CALIX_IE_tx_notification                          2036u  /* tx-notification */
#define IPFIX_CALIX_IE_rx_notification                          2037u  /* rx-notification */
#define IPFIX_CALIX_IE_tx_keepalive                             2038u  /* tx-keepalive */
#define IPFIX_CALIX_IE_rx_keepalive                             2039u  /* rx-keepalive */
#define IPFIX_CALIX_IE_ospf_stat_aid                            2040u  /* ospf-stat-aid */
#define IPFIX_CALIX_IE_sample_time_2041                         2041u  /* sample-time */
#define IPFIX_CALIX_IE_rx_hello                                 2042u  /* rx-hello */
#define IPFIX_CALIX_IE_tx_hello                                 2043u  /* tx-hello */
#define IPFIX_CALIX_IE_rx_db_des                                2044u  /* rx-db-des */
#define IPFIX_CALIX_IE_tx_db_des                                2045u  /* tx-db-des */
#define IPFIX_CALIX_IE_rx_ls_req                                2046u  /* rx-ls-req */
#define IPFIX_CALIX_IE_tx_ls_req                                2047u  /* tx-ls-req */
#define IPFIX_CALIX_IE_rx_ls_upd                                2048u  /* rx-ls-upd */
#define IPFIX_CALIX_IE_tx_ls_upd                                2049u  /* tx-ls-upd */
#define IPFIX_CALIX_IE_rx_ls_ack                                2050u  /* rx-ls-ack */
#define IPFIX_CALIX_IE_tx_ls_ack                                2051u  /* tx-ls-ack */
#define IPFIX_CALIX_IE_route_summary_stataid                    2052u  /* route-summary-stataid */
#define IPFIX_CALIX_IE_address_family                           2053u  /* address-family */
#define IPFIX_CALIX_IE_bgp                                      2054u  /* bgp */
#define IPFIX_CALIX_IE_connected                                2055u  /* connected */
#define IPFIX_CALIX_IE_isis                                     2056u  /* isis */
#define IPFIX_CALIX_IE_ospf                                     2057u  /* ospf */
#define IPFIX_CALIX_IE_static                                   2058u  /* static */
#define IPFIX_CALIX_IE_total                                    2059u  /* total */
#define IPFIX_CALIX_IE_lldp_agent_aid                           2060u  /* lldp-agent-aid */
#define IPFIX_CALIX_IE_dest_agent                               2061u  /* dest-agent */
#define IPFIX_CALIX_IE_too_many_neighbors                       2062u  /* too-many-neighbors */
#define IPFIX_CALIX_IE_tx_credit                                2063u  /* tx-credit */
#define IPFIX_CALIX_IE_tx_ttl                                   2064u  /* tx-ttl */
#define IPFIX_CALIX_IE_tx_ttr                                   2065u  /* tx-ttr */
#define IPFIX_CALIX_IE_tx_fast                                  2066u  /* tx-fast */
#define IPFIX_CALIX_IE_tx_state                                 2067u  /* tx-state */
#define IPFIX_CALIX_IE_tx_tmr_state                             2068u  /* tx-tmr-state */
#define IPFIX_CALIX_IE_rx_state                                 2069u  /* rx-state */
#define IPFIX_CALIX_IE_ageouts                                  2070u  /* ageouts */
#define IPFIX_CALIX_IE_in_discards                              2071u  /* in-discards */
#define IPFIX_CALIX_IE_in_errors                                2072u  /* in-errors */
#define IPFIX_CALIX_IE_in_total                                 2073u  /* in-total */
#define IPFIX_CALIX_IE_out_total                                2074u  /* out-total */
#define IPFIX_CALIX_IE_tlvs_discarded                           2075u  /* tlvs-discarded */
#define IPFIX_CALIX_IE_tlvs_unrecognized                        2076u  /* tlvs-unrecognized */
#define IPFIX_CALIX_IE_pdu_length_errors                        2077u  /* pdu-length-errors */
#define IPFIX_CALIX_IE_rate_violations                          2078u  /* rate-violations */
#define IPFIX_CALIX_IE_lldp_neighbor_aid                        2079u  /* lldp-neighbor-aid */
#define IPFIX_CALIX_IE_agent_reference                          2080u  /* agent-reference */
#define IPFIX_CALIX_IE_system_name_tlv                          2081u  /* system-name-tlv */
#define IPFIX_CALIX_IE_port_id_tlv                              2082u  /* port-id-tlv */
#define IPFIX_CALIX_IE_management_address_tlv                   2083u  /* management-address-tlv */
#define IPFIX_CALIX_IE_ttl_tlv                                  2084u  /* ttl-tlv */
#define IPFIX_CALIX_IE_rx_info_tlv                              2085u  /* rx-info-tlv */
#define IPFIX_CALIX_IE_mib_changes                              2086u  /* mib-changes */

#endif /* IPFIX_ENTERPRISE_CALIX_H */
